Home/urls.py
from django.urls import path
from .views import Home

app_name = 'homeapp'

urlpatterns =[
    path('',Home,name='index'),
    
]

gaauDar/urls.py
from django.urls import path
from .views import interestCalculate,keepRecord,transaction,interestRate

app_name= 'app1'

urlpatterns =[
    path('interestCalculate/',interestCalculate,name='interestCalculate'),
    path('keepRecord/',keepRecord,name='keepRecord'),
    path('transaction/',transaction,name='transaction'),
    path('interestRate',interestRate,name='interestRate'),
    
    
]

meterByaaj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('getRate/',include('gaauDar.urls',namespace='app1')),
    path('',include('Home.urls',namespace='homeapp')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Home/models.py
from django.db import models

# Create your models here.

gaauDar/models.py
from django.db import models

class Icalc(models.Model):
    principle = models.CharField(max_length=100)
    rate = models.CharField('interest Rate' ,max_length=100)
    initial_time = models.DateField('सापटि लगेको समय')
    final_time = models.DateField('पैशा बुजाएको समय')

gaauDar/forms.py
from django import forms
from .models import Icalc


class IcalcForm(forms.ModelForm):
    class Meta:
        model = Icalc
        fields = '__all__'

Home/views.py
from django.shortcuts import render


# Create your views here.
def Home(request):

    return render(request,'home.html')

gaauDar/views.py
from django.shortcuts import render
from .forms import IcalcForm

def interestCalculate(request):
    form = IcalcForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        form.save()
        form = IcalcForm()
    
    return render(request,'index.html',{'form':form })

def keepRecord(request):

    return render(request,'recordMenu.html')

def transaction(request):
    return render(request,'transit.html')

def interestRate(request):
    
    return render(request,'rateInfo.html')

Home/templates/home.html
{% extends 'base.html' %}
    {% block title %}
        meterByaaj
    {% endblock %}
    


    {% block content %}
    <div class="homeContent">
        <a href="{% url 'app1:interestCalculate' %}"><input id="homeButtons" type="submit" value="ब्याज हिसाब गर्नुहोस्" name="interestCalculate"></a>
        <a href="{% url 'app1:keepRecord' %}"><input id="homeButtons" type="submit" value="रेकर्ड राख्नुहोस्" name="Record"></a>
        <a href="{% url 'app1:transaction' %}"><input id="homeButtons" type="submit" value="जम्मा कारोबार हेर्नुहोस्" name="transaction"></a>
        <a href="{% url 'app1:interestRate' %}"><input id="homeButtons" type="submit" value="ब्याजदर मिलाऊनुहोस्" name="interestRate"></a>
    </div>
    {% endblock %}

gaauDar/templates/index.html
{% extends 'base.html' %}
{% block content %}
<h1>you can calculate interest here </h1>
<form enctype="multipart/form-data" method="POST" action="Isave">{% csrf_token %}
    {{ form }}<br>
    <input type="submit" name="Submit" value="Submit">
</form>
{% endblock %}

gaauDar/templates/rateInfo.html
<h1>Interest Rate info </h1>
<h5>you can manage Interest Rate here </h5>

gaauDar/templates/recordMenu.html
<marquee>hello i am record <Menu>hello hello </Menu></marquee>

gaauDar/templates/transit.html
<h3>i am <strong>transaction</strong></h3>